### ISSUE TITLE
Suggestions for ItemProcessor

### ISSUE THREAD

**Issue by Deathawaits4** [AndroidQuazar/VanillaExpandedFramework#11]
Currently the ItemProcessor does not support a yield higher than a stacksize. As soon as the Yield is higher than the max Stack of the item, it throws an error and truncates the stack. 
A suggestion would be to instead of just trying to use a stack higher than whats allowed, the stack gets split as when you are butchering.

**Comment by juanosarg** [comment]
That's weird, we specifically added a patch so the game doesn't truncate stacks. It seems to be working on the Mechanoids mod

**Comment by Deathawaits4** [comment]
> That's weird, we specifically added a patch so the game doesn't truncate stacks. It seems to be working on the Mechanoids mod

I have completely redone the building now and it seems to be working now. I will close the issue
