### ISSUE TITLE
Symbols Creator - Too many defs

### ISSUE THREAD

**Issue by idkman2021** [AndroidQuazar/VanillaExpandedFramework#21]
Too many KCSG.SymbolDef; over 65535
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.DefDatabase`1<KCSG.SymbolDef>:Add (KCSG.SymbolDef)
KCSG.SymbolDefsCreator:AddDef (KCSG.SymbolDef)
KCSG.SymbolDefsCreator:CreateAllSymbolsForDef (Verse.ThingDef)
KCSG.SymbolDefsCreator:CreateSymbolsFor (string)
KCSG.SymbolDefsCreator:Run ()
KCSG.SymbolDefsCreator:.cctor ()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor (System.RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_3 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Comment by idkman2021** [comment]
https://gist.github.com/HugsLibRecordKeeper/fbcfc6280af32eace8ed7847bb6b18cf

**Comment by KylianB** [comment]
Activate Custom Structure Generation Verbose logging, reopen the game and share a log once again, please.

**Comment by idkman2021** [comment]
> Activate Custom Structure Generation Verbose logging, reopen the game and share a log once again, please.

https://gist.github.com/idkman2021/a0e7d42014d1c48cdea28ab6fccaad63

**Comment by KylianB** [comment]
The version you have doesn't allow me to know what's causing the Symbols Creator to create more than 65535 errors.
Please either wait for the next framework update, or try using the GitHub version of the mod. Keep the verbose logging on, and please share a new log.
