### ISSUE TITLE
VFECore.FactionDefExtension allowedBiomes not working with ReGrowth: Wastelands biome

### ISSUE THREAD

**Issue by Trokare** [AndroidQuazar/VanillaExpandedFramework#23]
Hello,

I tried to create a faction that would spawn only on the wasteland biome created by ReGrowth: Wastelands using the parameters :
`
    <modExtensions>
      <li Class="VFECore.FactionDefExtension">
        <allowedBiomes>
			<li>RG-W_Wasteland</li>
        </allowedBiomes>
      </li>
    </modExtensions>
`
It blocked the faction spawn, visibly the modded biome isn't recorganized while the vanilla biomes are ok.

**Comment by Taranchuk** [comment]
You need to change RG-W_Wasteland BiomeDef to increase settlementSelectionWeight. And then patch all faction defs except these you want to disallow them from spawning on it. I think github isn't suitable for a such question, better to join Vanilla Testing Expanded discord as a framework enthusiast and ask your questions here.
https://discord.gg/DwYY99Vf

**Comment by Trokare** [comment]
Thanks, it worked
