### ISSUE TITLE
Stuff commonality extension question

### ISSUE THREAD

**Issue by idkman2021** [AndroidQuazar/VanillaExpandedFramework#27]
what units is it in? Does `<structureGenerationCommonalityOffset>100</structureGenerationCommonalityOffset>` mean the offset is 100 or 1?
`<structureGenerationCommonalityFactor>100</structureGenerationCommonalityFactor> `- multiplied by 100 or by 1 (100%)?

**Comment by Taranchuk** [comment]
these are 100
