### ISSUE TITLE
Red errors on load

### ISSUE THREAD

**Issue by VilcsiTH** [AndroidQuazar/VanillaExpandedFramework#59]
Tested with only Harmony, Core, Royalty and Ideology loaded, the framework causes 9 red errors on load into main menu.

It seems to be loosely related to settlement/faction/etc. generation, but it also seems to have issues with settlements overall. I tried loading other vanilla expanded mods besides just the framework, but the issue remained.

Log included below.

[mainmenu.log](https://github.com/AndroidQuazar/VanillaExpandedFramework/files/9567951/mainmenu.log)

**Comment by Taranchuk** [comment]
I think you need to ensure that the framework is up to date.

**Comment by VilcsiTH** [comment]
I was out of date, you were right, I did not notice we had an update yesterday. However, the errors remained after updating, sadly.

**Comment by Taranchuk** [comment]
How do you update mods on GOG?

**Comment by VilcsiTH** [comment]
I use steamcmd to grab and update workshop mods. In theory, it should be the same procedure that the normal steam client uses.

The issues remaining after the update did make me think that the workshop folder was potentially corrupted, so I tracked down the folder with the workshop ID and deleted it. Upon updating with steamcmd, I can now load normally, without issues.

Thank you for your help! Looks like this is something I have to keep an eye on in the future.
