### ISSUE TITLE
Hired pawns in mental state(drug or alcohol breaks) 

### ISSUE THREAD

**Issue by artur-shamigulov** [AndroidQuazar/VanillaExpandedFramework#62]
Hello, I faced with problem when a contract was ended or cancelled some hired pawn could be in mental states. Usually they get command to leave map, but because it is conflicted with breaks behaviour (drink beer for example), pawns stick in loop with to commands leave map and drink beer(or something else).
`                else if (pawn.health.capacities.CapableOf(PawnCapacityDefOf.Moving))
                {
`
HiringContractTracker.cs row #73
You could check it there( && !pawn.InMentalState), or simply cancel the state.

**Comment by legodude17** [comment]
Please use [Vanilla-Expanded/VanillaExpandedFramework](https://github.com/Vanilla-Expanded/VanillaExpandedFramework).
